In [1]:
from utils.utility import get_labels
import pandas as pd

labels_df = get_labels("train")
labels_df.head()

,class,x_center,y_center,width,height,image_id
0,0,0.554296875,0.671875,0.05546875,0.05859375,bb929c7dbc4688686a3a985554ca7f1b
1,0,0.446875,0.9052734375,0.0484375,0.037109375,f3d4aca4eb718586b46d1f7792f622f3
2,0,0.2234375,0.44140625,0.0421875,0.037109375,6bea25ec4fef4fa26ea2b535d4624f26
3,0,0.405078125,0.74560546875,0.08515625,0.0791015625,fc0f7910801c6373f5c78a1ed20042cd
4,0,0.4046875,0.07568359375,0.028125,0.0263671875,9f76a910ba3a542c14a0e2915b261f78

In [2]:
from utils.utility import convert_labels_to_pixel

converted = convert_labels_to_pixel(labels_df)

In [3]:
from utils.utility import convert_labels_to_yolo

convert_labels_to_yolo(converted)

,x_center,y_center,width,height,image_id,class
0,0.554297,0.671875,0.055469,0.058594,bb929c7dbc4688686a3a985554ca7f1b,0
1,0.446875,0.905273,0.048438,0.037109,f3d4aca4eb718586b46d1f7792f622f3,0
2,0.223438,0.441406,0.042188,0.037109,6bea25ec4fef4fa26ea2b535d4624f26,0
3,0.405078,0.745605,0.085156,0.079102,fc0f7910801c6373f5c78a1ed20042cd,0
4,0.404687,0.075684,0.028125,0.026367,9f76a910ba3a542c14a0e2915b261f78,0
...,...,...,...,...,...,...
18394,0.370312,0.155273,0.053125,0.039062,759d167851d02deef160190bd177c45d,0
18395,0.538672,0.460938,0.124219,0.060547,51439d7d25110390ae7d25378a36cc0e,0
18396,0.727734,0.714844,0.339844,0.570312,30c02b4d919e92849749f96f4493dff0,0
18397,0.684766,0.252441,0.153906,0.143555,c0fb9688d374249e0e954aa948f5d3b2,0
18398,0.164062,0.387207,0.032813,0.049805,4ca4a36bc69d962196a2c681a6b49a13,0